#!/bin/bash
set -e

python /opt/llama.cpp/convert_hf_to_gguf.py function-270m --outfile function-270m.gguf --outtype bf16
/opt/llama.cpp/build/bin/llama-quantize function-270m.gguf function-270m-Q4_K_M.gguf Q4_K_M

