#!/bin/sh

echo stopping ai chat service ...
systemctl stop ai-chat.service

# echo stopping jarvis service ...
# systemctl stop jarvis.service

echo stopping function service ...
systemctl stop function.service

echo stopping router service ...
systemctl stop router.service

echo stopping router socket service ...
systemctl stop router-socket.service

